added the displacement vector calculation added a status flag for new maxima
need to be fixed:
shiftX = newMaxima[:, 1] - maxima[:, 1]
ValueError: operands could not be broadcast together with shapes (20,) (19,)